env:
  global:
    - CC_TEST_REPORTER_ID=53d40fe6f47334e072c8cbd2b5d4a3e78066d5d36dc7283cff43c6479b45e156

language: ruby
rvm:
  - 2.6.3

before_install: gem install bundler
bundler_args:
  --without development --jobs=3 --retry=3 --path=../vendor/bundle
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
